import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../../shared/theme/app_spacing.dart';
import '../../domain/entities/job.dart';
import '../providers/jobs_provider.dart';
import '../../../auth/presentation/providers/auth_provider.dart';

class CreateJobScreen extends ConsumerStatefulWidget {
  const CreateJobScreen({super.key});

  @override
  ConsumerState<CreateJobScreen> createState() => _CreateJobScreenState();
}

class _CreateJobScreenState extends ConsumerState<CreateJobScreen> {
  final _titleCtrl = TextEditingController();
  final _descCtrl = TextEditingController();
  final _locationCtrl = TextEditingController();
  String _contractType = 'full_time';
  bool _isLoading = false;

  @override
  void dispose() {
    _titleCtrl.dispose();
    _descCtrl.dispose();
    _locationCtrl.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (_titleCtrl.text.trim().isEmpty || _descCtrl.text.trim().isEmpty || _locationCtrl.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Compila tutti i campi')));
      return;
    }

    final authState = ref.read(authStateProvider).valueOrNull;
    if (authState == null) return;

    setState(() => _isLoading = true);

    try {
      final job = Job(
        id: '', // Generated by Firestore
        companyId: authState.uid,
        companyName: authState.displayName ?? 'Azienda',
        companyLogoUrl: authState.photoUrl,
        title: _titleCtrl.text.trim(),
        description: _descCtrl.text.trim(),
        category: 'Non specificata', // Can add a field for this
        contractType: ContractType.fromString(_contractType),
        location: _locationCtrl.text.trim(),
        latitude: 0,
        longitude: 0,
        geohash: '',
        status: JobStatus.active,
        applicationsCount: 0,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      await ref.read(jobsRepositoryProvider).createJob(job);
      
      // Invalidate to refresh company jobs list
      ref.invalidate(companyJobsProvider(authState.uid));
      ref.invalidate(recentJobsProvider);

      if (mounted) {
        context.pop();
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Offerta pubblicata con successo!')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Errore: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Crea Nuova Offerta'),
      ),
      body: SingleChildScrollView(
        padding: AppSpacing.pagePadding,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            TextField(
              controller: _titleCtrl,
              decoration: const InputDecoration(
                labelText: 'Titolo Offerta',
                hintText: 'Es: Frontend Developer Flutter',
              ),
            ),
            AppSpacing.vGapMd,
            TextField(
              controller: _descCtrl,
              maxLines: 5,
              decoration: const InputDecoration(
                labelText: 'Descrizione',
                hintText: 'Descrivi il ruolo, le responsabilità e i requisiti...',
              ),
            ),
            AppSpacing.vGapMd,
            DropdownButtonFormField<String>(
              value: _contractType,
              decoration: const InputDecoration(labelText: 'Tipo di Contratto'),
              items: const [
                DropdownMenuItem(value: 'full_time', child: Text('Full-time')),
                DropdownMenuItem(value: 'part_time', child: Text('Part-time')),
                DropdownMenuItem(value: 'freelance', child: Text('Freelance')),
              ],
              onChanged: (val) {
                if (val != null) setState(() => _contractType = val);
              },
            ),
            AppSpacing.vGapMd,
            TextField(
              controller: _locationCtrl,
              decoration: const InputDecoration(
                labelText: 'Sede di lavoro (Città o Indirizzo)',
                hintText: 'Es: Milano (MI)',
                prefixIcon: Icon(Icons.location_on_outlined),
              ),
            ),
            AppSpacing.vGapXxl,
            ElevatedButton(
              onPressed: _isLoading ? null : _submit,
              style: ElevatedButton.styleFrom(
                padding: const EdgeInsets.symmetric(vertical: 16),
              ),
              child: _isLoading 
                  ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2))
                  : const Text('Pubblica Offerta', style: TextStyle(fontSize: 16)),
            ),
          ],
        ),
      ),
    );
  }
}
